### PR TITLE
Regenerate with JSON-LD fix enabled

### PR DESCRIPTION
**Pull request by berezovskyi**
Uses 2.4.0.M2-SNAPSHOT, needed to apply the recent fix for non-working
JSON-LD.

Also removes spaces from the DS resources.

---
This change is [Reviewable](https://reviewable.io/reviews/oslc/lyo-adaptor-sample-modelling/20)

### CODE REVIEW

**Comment by jadelkhoury** [comment]
-1 
There are more changes in this request than I would have expected. Need to investigate.

**Comment by berezovskyi** [comment]
True, the change on the model was unexpected but I assumed that preserving the RDF output consistency would have a higher priority. Do we need to hold the release of the Designer while you investigate?

--
/Andrew

On 25 Nov 2018, at 08:09, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


-1
There are more changes in this request than I would have expected. Need to investigate.

**Comment by jadelkhoury** [comment]
No. I think I know what this is about. Proceed with 2.4.0

**Comment by berezovskyi** [comment]
Do I need to put a note about a change in how the shapes with spaces are handled by the generator then?

--
/Andrew

On 2018-11-25 , at 13:11, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


No. I think I know what this is about. Proceed with 2.4.0

**Comment by jadelkhoury** [comment]
Ok. Maybe the title of the shape becomes with “_”.
But the rdfs:class is “test case” in the new behavior. This produces an error when one uses JMH to Marshall.
The remedy in the sample project is indeed to remove the spaces in the names. I just have not bothered to update the repo with that change yet.

On 25 Nov 2018, at 13:28, Andrew Berezovskyi <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think this is the behaviour I have encountered in this case.

Before the change in question was made to the generator, the "Test Case" shape title in the model became a TestCase RDF URI. After the change, the "Test Case" shape title in the model became a Test_Case. Therefore, I had to remove the space to bring back the original URI. So, the white space is still manipulated.

I am not suggesting to do anything about it, just to reflect it in the release notes.

**Comment by berezovskyi** [comment]
Got it, thanks

**Comment by berezovskyi** [comment]
@jadelkhoury shall I try to resolve merge conflicts or do you want to scrap this PR?

**Comment by jadelkhoury** [comment]
let's scrap this pull request. All changes here seem to be reflected in the latest code generator.
I try to regularly re-generate this model to keep it up to date with the latest changes in LyoDesigner. No need to do a pull request on that. I simply make sure it runs, plus do a thourough code review of the changes generated

**Pull request closed without merging**
