### PR TITLE
Update of toolchain model to use the newly suggested keys for references.

### PR DESCRIPTION
**Pull request by jadelkhoury**
Update of toolchain model to use the newly suggested keys for references.

This is how models look like once/if we apply the patch https://github.com/eclipse/lyo.designer/pull/72

---
This change is [Reviewable](https://reviewable.io/reviews/oslc/lyo-adaptor-sample-modelling/28)

### CODE REVIEW

**Comment by berezovskyi** [comment]
How manual was this?

**Comment by jadelkhoury** [comment]
> How manual was this?

no manual work. I was impressed by EMF.
* You can open old files, no problems.
* You can do graphical changes to the model. No problems, and saved file still follows old style of referencing.
* Once you do the simplest change to the emf model (ex. add/remove a resource), the whole file gets to use new way of referencing.

**Comment by berezovskyi** [comment]
@jadelkhoury are you waiting for me on this?

**Comment by jadelkhoury** [comment]
-1
on hold until https://github.com/eclipse/lyo.designer/pull/72 is solved.

**Comment by berezovskyi** [comment]
Merged latest changes from master and 4.0.0

**Comment by jadelkhoury** [comment]
@berezovskyi Why merging from Master to here? I will only confuse me.
I will not proceed on this pull-request, and will most likely push a new branch since we are aiming for a new approach.

**Comment by berezovskyi** [comment]
My bad. We only needed to merge from `4.0.0-snapshot`.

**Comment by berezovskyi** [comment]
I guess this was already merged in in LyoD? Closing.

**Pull request closed without merging**
