### PR TITLE
2 approaches on how to relate a ServiceProvider to a TRS resource.

### PR DESCRIPTION
**Pull request by jadelkhoury**
Here are 2 suggestions to your need to relate a ServiceProvider to a TRS.

The easiest is to extend the existing ServiceProvider resource with additional properties.
See the added code in the method ServiceProvider1sFactory::createServiceProvider. The code is not in a user-proptected-area, and hence will be lost upon regeneration. But that we can fix.

Do a GET on http://localhost:8081/adaptor-rm/services/serviceProviders1/0
notice the new triple 
<...services/someLocalPart> <...services//someTRSURI> ;

The second approach is to define a new resource that relates ServiceProviders with TRS resources. One can even have a ServiceProvider that can be used to Query and GET such resources.
For that, have a look at the model of the RM adaptor (and the resulting code). 
Note that once we have more than 1 type of ServiceProviders, the class names get ugly in Lyo Designer :-(

---
This change is [Reviewable](https://reviewable.io/reviews/oslc/lyo-adaptor-sample-modelling/15)

### CODE REVIEW

**Comment by berezovskyi** [comment]
sorry, totally missed this one

**Comment by berezovskyi** [comment]
just quickly went over all the generated code and I don't see any code related to the handling of the TRS Base or CL. Am I missing something? Shall we just generate some code that extends https://github.com/eclipse/lyo.trs-server? Here is how I do it: https://github.com/EricssonResearch/scott-eu/blob/master/lyo-services/webapp-twin/src/main/java/se/ericsson/cf/scott/sandbox/twin/trs/TwinTrsServerService.java

**Comment by jadelkhoury** [comment]
This is a long time ago. Let’s talk instead

**Comment by jadelkhoury** [comment]
> I guess we abandon this patch; I will use `queryProviderToTRSs ` as a guide for myself.
@berezovskyi 
This was not meant to be a pull request. I wanted to show you 2 alternatives on how ServiceProvider can relate to a TRS. Let's delete, since I believe we have already discussed this.

**Pull request closed without merging**
