### PR TITLE
[Not a Pull Request] Simpler class names

### PR DESCRIPTION
**Pull request by jadelkhoury**
This is to illustrate the changes from the LyoDesigner changes requested under https://github.com/eclipse/lyo.designer/pull/237

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi is there a reason jad.el.khoury_at_scania cannot create  a pull request here?

**Comment by berezovskyi** [comment]
You can always make a PR. You are not able to push a branch directly without making a fork because that account is not part of the org. I will add you (this is not `eclipse/` org).

**Comment by berezovskyi** [comment]
@jadelkhoury by the way, you are an admin in this org, so you could have sent an invite yourself :)

**Comment by jad-elkhoury** [comment]
> You can always make a PR. You are not able to push a branch directly without making a fork because that account is not part of the org. I will add you (this is not `eclipse/` org).

Yes, but I am too lazy to create my own repo. But thanks. now I joined.

**Comment by berezovskyi** [comment]
Upstream PR merged

**Pull request closed without merging**
