### PR TITLE
Add read-only CORS headers for UI preview

### LINKED ISSUE #16: CORS is blocking UI preview
image

https://www.baeldung.com/cors-in-jax-rs is only available in JAX-RS 2.0 and handlers will have to migrated

### PR DESCRIPTION
**Pull request by berezovskyi**
closes #16

---
This change is [Reviewable](https://reviewable.io/reviews/oslc/lyo-adaptor-sample-modelling/18)

### CODE REVIEW

**Comment by jadelkhoury** [comment]
@berezovskyi why are we doing this? The suggested changes will be lost upon a re-generation, which defies the point of this repo. (To illustrate the use of alto.designer in the wiki) 
If we need this fix, it should be in Lyo.designer, right?

**Comment by berezovskyi** [comment]
I wanted to test lyo 2.4.0.m1 on this repo and stumbled on this CORS problem

**Comment by jadelkhoury** [comment]
I see. So are you suggesting we introduce this code change into the generator? Is it tested?
And, just to be sure, is this in anyway related to these 2 bugs that we have earlier fixed?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532688
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532687

**Comment by berezovskyi** [comment]
Yes, I did verify the fix but not extensively. The CORS headers need to be added to every response that is embedded in an iframe, so I'd suggest to put them in the generator. But the method I'd probably put somewhere in Lyo library code.

--
/Andrew

On 12 Nov 2018, at 09:20, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. So are you suggesting we introduce this code change into the generator? Is it tested?
And, just to be sure, is this in anyway related to these 2 bugs that we have earlier fixed?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532688
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532687

**Comment by berezovskyi** [comment]
Not related to these 2 in any way.

--
/Andrew

On 12 Nov 2018, at 09:20, Jad El-khoury <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. So are you suggesting we introduce this code change into the generator? Is it tested?
And, just to be sure, is this in anyway related to these 2 bugs that we have earlier fixed?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532688
https://bugs.eclipse.org/bugs/show_bug.cgi?id=532687

**Comment by jadelkhoury** [comment]
Integrated as part of LyoDesigner already [F cors support #58](https://github.com/eclipse/lyo.designer/pull/58)

**Pull request closed without merging**
